version: "3.5"
services:
  db:
    image: docker.io/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
  s3:
    image: docker.io/rustfs/rustfs
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_CONSOLE_ENABLE=true
